services:
  postgres:
    image: postgres:16-alpine
    container_name: smile_saviors_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: smile_saviors_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
